"""Domain models for PIE AI Reasoning Engine, Chat Sessions, and Intent Classification."""

from enum import Enum
from typing import Any
from datetime import datetime
from pydantic import BaseModel, Field


class ChatRole(str, Enum):
    """Role in a conversational exchange."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class QueryIntent(str, Enum):
    """Cognitive intent detected from user input."""
    ARCHITECTURE = "architecture"          # Pipeline workflow, SaaS touchpoints, schedule
    DEBUGGING = "debugging"                # Technical step sequence, SQL queries, stored procedures, retries
    IMPACT = "impact"                      # What-if deletion, blast radius, broken activities, remediation
    SEARCH = "search"                      # Find datasets by file type (e.g. onprem CSV), schema, or folder
    CODE_GEN = "code_gen"                  # Generate PySpark, SQL, or dbt migration code
    SECURITY_AUDIT = "security_audit"      # Orphan pipelines, zero retries, Key Vault compliance
    GENERAL = "general"                    # General platform questions


class LLMProviderType(str, Enum):
    """Supported LLM backend providers."""
    MOCK = "mock"
    AZURE_OPENAI = "azure_openai"
    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    GEMINI = "gemini"
    NVIDIA = "nvidia"


class ChatMessage(BaseModel):
    """Individual conversational message."""
    role: ChatRole
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class LLMConfig(BaseModel):
    """Configuration for LLM reasoning."""
    provider: LLMProviderType = LLMProviderType.MOCK
    model: str = "gpt-4o-mini"
    temperature: float = 0.1
    max_tokens: int = 4096
    api_key: str | None = None
    endpoint: str | None = None
    azure_endpoint: str | None = None
    api_version: str | None = None
    google_api_key: str | None = None
    nvidia_api_key: str | None = None


class ReasoningResponse(BaseModel):
    """Output generated by the PIE AI Reasoning Engine."""
    user_query: str
    detected_intent: QueryIntent
    target_asset: str | None = None
    response_markdown: str
    cited_assets: list[str] = Field(default_factory=list)
    tokens_consumed: int = 0
    grounding_score: float = 100.0  # 100% deterministic metadata grounding
    latency_ms: float = 0.0
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class Spike5Result(BaseModel):
    """Persisted output artifact for Spike 5."""
    spike_id: str = "spike_5_ai_reasoning_and_chat"
    status: str = "SUCCESS"
    executed_at: datetime = Field(default_factory=datetime.utcnow)
    provider_used: str
    sample_interactions: list[ReasoningResponse] = Field(default_factory=list)
