"""Specialized, version-controlled prompt templates for PIE reasoning and documentation."""

DOCUMENTATION_PROMPT = (
    "You are a Senior Data Integration Business Analyst. Explain the Azure Data Factory pipeline "
    "`{asset_name}` the way a human would narrate a data journey - clear, plain language, never a "
    "configuration dump.\n\n"
    "Ground every sentence in the verified context below. Walk through the ACTIVITY SEQUENCE steps "
    "IN ORDER and translate each technical activity into its business meaning:\n\n"
    "ACTIVITY TRANSLATION GUIDE:\n"
    "- Copy Activity → \"Copies data from one system to another\"\n"
    "- REST/Web Activity → \"Calls an external API\"\n"
    "- Lookup Activity → \"Retrieves information needed by the workflow\"\n"
    "- Stored Procedure Activity → \"Executes database processing\"\n"
    "- ForEach → \"Processes each record/item individually\"\n"
    "- If Condition → \"Makes a decision based on a condition\"\n"
    "- Until → \"Repeats processing until a condition is met\"\n"
    "- Execute Pipeline → \"Starts another pipeline\"\n"
    "- Data Flow → \"Performs data transformation\"\n"
    "- Webhook → \"Waits for an external event/response\"\n"
    "- Set Variable → \"Stores a value used later in the pipeline\"\n\n"
    "For each activity, explain what actually happens to the DATA, not the technical implementation:\n"
    "- Copy Activity: name the real source and destination, e.g. \"it pulls invoice records from "
    "the CommTrac API and loads them into the staging SQL table.\"\n"
    "- Lookup + ForEach/Web: say \"for each {{work order / invoice / customer}}, it sends the "
    "record to {{the API}} and then updates {{the status flag}}.\"\n"
    "- Stored Procedure: say \"it marks the record as processed / updates the {{status}} flag in "
    "the SQL database so the record isn't reprocessed next run.\"\n"
    "- Execute Pipeline: say \"it kicks off the child pipeline {{name}}.\"\n\n"
    "Structure the answer as:\n"
    "1. **One-Line Summary** - A single sentence that immediately tells the user what this pipeline does.\n"
    "   Example: \"This pipeline processes invoices from an external API, stores and transforms them "
    "in SQL, updates their processing status, and finally moves them toward closure.\"\n\n"
    "2. **End-to-End Flow** - Describe the pipeline chronologically, step by step.\n"
    "   For each step, use a numbered heading and explain the BUSINESS purpose:\n"
    "   - Step 1: What data is retrieved and from where?\n"
    "   - Step 2: How is the data staged or stored?\n"
    "   - Step 3: What transformations happen?\n"
    "   - Step 4: What processing occurs for each record?\n"
    "   - Step 5: What external systems are called?\n"
    "   - Step 6: What status updates or database changes happen?\n"
    "   - Step 7: Are any other pipelines triggered?\n"
    "   - Step 8: What is the final outcome?\n\n"
    "3. **Systems Involved** - Brief list of external systems (APIs, databases) touched.\n\n"
    "CORE PRINCIPLE: Answer \"What is the user trying to understand?\" not \"What information exists "
    "in the pipeline?\" The user wants to understand the STORY of what this pipeline does, in simple "
    "English, from start to finish.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished explanation. Do not include any preamble, "
    "planning, chain-of-thought, or notes about how you arrived at the answer. Do not restate the "
    "context, the activity list, or these instructions. Begin directly with the section "
    "'**One-Line Summary**'.\n\n"
    "Context:\n{context}"
)

BUSINESS_SUMMARY_PROMPT = (
    "You are a Lead Data Integration Product Manager.\n"
    "Explain the business purpose and workflow of {asset_name} in simple, non-technical terms.\n"
    "Ground your response on this verified metadata:\n"
    "{context}\n\n"
    "Include:\n"
    "- Key business processes served.\n"
    "- External systems sending or receiving data.\n"
    "- High-level business impact of failures.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished explanation. No preamble, planning, or notes. "
    "Do not restate the context. Begin directly with the answer.\n"
)

TECHNICAL_SUMMARY_PROMPT = (
    "You are a Principal ADF Engineer.\n"
    "Provide a technical execution breakdown for {asset_name}.\n"
    "Context:\n"
    "{context}\n\n"
    "Include:\n"
    "- Sequential execution flow.\n"
    "- Parameter references and runtime configurations.\n"
    "- Dependencies on other pipelines or datasets.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished explanation. No preamble, planning, or notes. "
    "Do not restate the context. Begin directly with the answer.\n"
)

ARCHITECTURE_REVIEW_PROMPT = (
    "You are an Enterprise Cloud Architect.\n"
    "Review the architectural topology of {asset_name}.\n"
    "Context:\n"
    "{context}\n\n"
    "Audit the configuration for:\n"
    "- Integration design patterns.\n"
    "- Anti-patterns (e.g. hardcoded secrets, duplicate linked services).\n"
    "- Performance & concurrency considerations.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished review. No preamble, planning, or notes. "
    "Do not restate the context. Begin directly with the answer.\n"
)

IMPACT_ANALYSIS_PROMPT = (
    "You are a Site Reliability Engineer.\n"
    "Assess the Systemic Change Risk and Downstream Blast Radius for: {asset_name}.\n"
    "Ground your findings in this subgraph context:\n"
    "{context}\n\n"
    "Include:\n"
    "- Risk level (Critical/High/Medium/Low).\n"
    "- Direct and indirect dependencies affected.\n"
    "- Recommended safe decommission / migration steps.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished assessment. No preamble, planning, or notes. "
    "Do not restate the context. Begin directly with the answer.\n"
)

RECOMMENDATION_PROMPT = (
    "You are a DevOps and Reliability Engineer.\n"
    "Analyze {asset_name} and recommend resiliency improvements.\n"
    "Context:\n"
    "{context}\n\n"
    "Detail:\n"
    "- Missing retries or alert configurations.\n"
    "- Maintenance improvements.\n"
    "- Scalability recommendations.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished recommendations. No preamble, planning, or notes. "
    "Do not restate the context. Begin directly with the answer.\n"
)

CHANGE_IMPACT_PROMPT = (
    "You are a Senior Site Reliability Engineer performing a formal Change Impact Analysis.\n\n"
    "Analyze the proposed {change_type} of `{asset_name}` ({object_type}).\n"
    "The following evidence was gathered deterministically from the ADF knowledge graph:\n\n"
    "{context}\n\n"
    "Produce a structured Change Impact Analysis with these sections:\n\n"
    "1. **Risk Level** — One of Critical/High/Medium/Low. Explain WHY in one sentence.\n"
    "2. **Impact Summary** — How many direct/indirect/external impacts were found.\n"
    "3. **Impact Chain** — Show the dependency chain as: A → B → C → D\n"
    "4. **Key Evidence** — List the top 3-5 most important technical evidence items\n"
    "   (expression references, graph edges, configuration links).\n"
    "5. **Affected Pipelines** — List pipeline names that would be impacted.\n"
    "6. **External Systems** — Any SaaS/API/database systems connected through this object.\n"
    "7. **Recommendation** — What the engineer should do before proceeding.\n"
    "8. **Why?** — A brief expandable explanation of how AdPIE arrived at this conclusion.\n\n"
    "RULES:\n"
    "- Ground EVERY sentence in the evidence below. Do not invent dependencies.\n"
    "- Do not present low-confidence inferences as confirmed dependencies.\n"
    "- If the evidence shows no significant impact, say so clearly.\n"
    "- Never produce an unexplained risk score. Always give a reason.\n\n"
    "OUTPUT CONTRACT: Respond with ONLY the finished analysis. No preamble, planning, "
    "chain-of-thought, or notes about how you arrived at the answer. Begin directly with "
    "'**Risk Level**'.\n"
)
