import os
from typing import Optional
from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(prefix="/settings", tags=["Settings"])

class APIKeysPayload(BaseModel):
    google: Optional[str] = ""
    azureEndpoint: Optional[str] = ""
    azureKey: Optional[str] = ""
    nvidia: Optional[str] = ""

@router.get("/keys")
async def get_keys() -> APIKeysPayload:
    return APIKeysPayload(
        google=os.getenv("GOOGLE_API_KEY", ""),
        azureEndpoint=os.getenv("AZURE_OPENAI_ENDPOINT", ""),
        azureKey=os.getenv("AZURE_OPENAI_API_KEY", ""),
        nvidia=os.getenv("NVIDIA_API_KEY", "")
    )

@router.post("/keys")
async def save_keys(payload: APIKeysPayload):
    # In a real app this would save to a secure vault or encrypted DB.
    # For this demo, we'll update the process environment so the LLM providers can see them immediately.
    # We will also attempt to update them in the local .env file (avoiding duplicates).
    
    env_updates = {
        "GOOGLE_API_KEY": payload.google,
        "AZURE_OPENAI_ENDPOINT": payload.azureEndpoint,
        "AZURE_OPENAI_API_KEY": payload.azureKey,
        "NVIDIA_API_KEY": payload.nvidia
    }
    
    # Update current process
    for k, v in env_updates.items():
        if v:
            os.environ[k] = v
            
    # Update .env file without duplicates
    try:
        env_file = ".env"
        env_content = {}
        
        # Read existing .env file
        if os.path.exists(env_file):
            with open(env_file, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, value = line.split("=", 1)
                        env_content[key.strip()] = value.strip()
        
        # Update with new values
        for k, v in env_updates.items():
            if v:
                env_content[k] = v
        
        # Write back to .env file
        with open(env_file, "w") as f:
            f.write("# Platform Intelligence Engine (PIE) - Environment Configuration\n")
            f.write("# Auto-generated by settings API\n\n")
            for k, v in sorted(env_content.items()):
                if v:
                    f.write(f"{k}={v}\n")
    except Exception as e:
        print(f"Warning: Failed to update .env file: {e}")
        
    return {"status": "ok"}
